In [8]:
# 共役転置のテスト
import numpy as np

np.random.seed(0)
# data = np.random.randn(2, 3, 4) + 1.j * np.random.randn(2, 3, 4)

data = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 0]], [[1, 2, 3, 4],[5, 0, 7, 8],[9, 10, 11, 12]]])
data_transposed = np.transpose(data, axes=(1, 0, 2)).conj()

print(data.shape[2])
print("元の形状:", data.shape) # 元の形状
print("共役転置後の形状:", data_transposed.shape) # 共役転置後の形状

print("data:\n", data)
print("data_transposed:\n", data_transposed)

print(np.einsum("mkt,knt->mn", data, data_transposed))

4
元の形状: (2, 3, 4)
共役転置後の形状: (3, 2, 4)
data:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11  0]]

 [[ 1  2  3  4]
  [ 5  0  7  8]
  [ 9 10 11 12]]]
data_transposed:
 [[[ 1  2  3  4]
  [ 1  2  3  4]]

 [[ 5  6  7  8]
  [ 5  0  7  8]]

 [[ 9 10 11  0]
  [ 9 10 11 12]]]
[[506 470]
 [470 614]]
