In [5]:
# 共役転置のテスト
import numpy as np

np.random.seed(0)
# data = np.random.randn(2, 3, 4) + 1.j * np.random.randn(2, 3, 4)

data = np.array([[[1, 22, 3, 4],[51, 61, 71, 81],[9, 10, 11, 0]], [[1, 2, 3, 4],[5, 0, 7, 8],[9, 101, 11, 12]]])
data_transposed = np.transpose(data, axes=(1, 0, 2)).conj()

# print(data.shape[2])
# print("元の形状:", data.shape) # 元の形状
# print("共役転置後の形状:", data_transposed.shape) # 共役転置後の形状

# print("data:\n", data)
# print("data_transposed:\n", data_transposed)

print(np.einsum("mkt,knt->kmn", data, data_transposed))
print(np.einsum("mkt,nkt->kmn", data, data))

[[[  510    70]
  [   70    30]]

 [[17924  1400]
  [ 1400   138]]

 [[  302  1212]
  [ 1212 10547]]]
[[[  510    70]
  [   70    30]]

 [[17924  1400]
  [ 1400   138]]

 [[  302  1212]
  [ 1212 10547]]]


In [9]:
import numpy as np

k = 7
n = 3
l = 4

np.random.seed(0)
kn = np.random.randn(7, 3)
nl = np.random.randn(3, 4)
ln = nl.transpose()
print(np.einsum("kn,nl->kl", kn, nl))
print(np.einsum("kn,ln->kl", kn, ln))

[[ 2.00915975  1.69487424 -1.01399889  3.74840899]
 [-2.68739459  1.87113919 -2.38225911  8.81644514]
 [ 0.68945866  0.79837144 -0.71582427  2.01610662]
 [ 2.19573232  0.58686336  0.21825726 -0.13833845]
 [ 0.97266278  0.73221169 -0.41973874  1.51981438]
 [-2.25629267  0.32501827 -0.60489205  3.22958878]
 [-2.30446358 -0.1640343  -1.03792003  1.66795464]]
[[ 2.00915975  1.69487424 -1.01399889  3.74840899]
 [-2.68739459  1.87113919 -2.38225911  8.81644514]
 [ 0.68945866  0.79837144 -0.71582427  2.01610662]
 [ 2.19573232  0.58686336  0.21825726 -0.13833845]
 [ 0.97266278  0.73221169 -0.41973874  1.51981438]
 [-2.25629267  0.32501827 -0.60489205  3.22958878]
 [-2.30446358 -0.1640343  -1.03792003  1.66795464]]
